config/routes.rb
Rails.application.routes.draw do

  resources :categories
  get 'store' => 'store#index'

  match 'store/:id' => 'store#show', :as => :store_product, :via => :get

  resources :apps

  root "demo#hello"

end

app/models/app.rb
class App < ActiveRecord::Base
	#attr_accessible :category_id

	belongs_to :category

	has_attached_file :image, styles: { 
		medium: "300x300>",
		thumb: "100x100>"
		}, 
		default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :apps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
    @categories = Category.order(:name)
  end

  # GET /apps/1/edit
  def edit
    @categories = Category.order(:name)
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name, :rating, :price, :image_url, :image, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  def hello
  	#@apps = App.all
  	@blind = App.where(:category_id => 1)
  	@sightImpairment = App.where(:category_id => 2) 
    @learningDisabled = App.where(:category_id => 3)
  	#@apps = App.find(params[:id])
  	@categories = Category.order(:name)
  	@products = App.order(:name)
  	#@productsss = App.find(params[:id])
  end
  
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@products = App.order(:name)
  end

  def show
  	@product = App.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/apps/_form.html.erb
<%= form_for@app, html: {multipart: true} do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Price</th>
      <th>Image url</th>
      <th>Category Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr class="<%= cycle('list-line-odd', 'list-line-even')%>">
        <td class="list-description">
        <dl>
          <dt><%= app.name %></dt>
          <ul><%= app.rating %></ul>
          <ul><%= app.price %></ul>
          <ul><%= app.category %></ul>
          <% if app.category %>
        <p>
          <ul><strong>Category:</strong><%= app.category.name %></ul>
        </p>
          <td><%= image_tag app.image.url(:thumb) %></td>

        </dl>
                <td class="image-description">
          <%= image_tag app.image_url, :class => 'list-image' %>
        </td>

        <% end %>

      <td class="list-actions">
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @app.image.url(:thumb) %>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @app.rating %>
</p>

<p>
  <strong>Price:</strong>
  <%= @app.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @app.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @app.category.name %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/demo/hello.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.ico' %>

    <title>Abillt</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Custom styles for this template -->
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

             
              <a class="navbar-brand" href="#">Abillt</a>
            </div>

          

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          
          </div>
        </nav>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <%= image_tag("BeMyEye.jpg", :alt => "rss feed" ) %>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
        
        <h2><Strong>Blind</Strong></h2>
        <p>
        <!-- link to view all the apps -->
        
          <p><a href="apps#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="jumbotron">
                <div class="container">

                  <div class="row">
                  <div class="row">

                  <% @blind.first(4).each do |app| %>
                  <div class="col-xs-3" >        
                  <a href="#" class="thumbnail" style="height:250px; width: 180px">         
                    <dl>
                    <td><%= image_tag app.image.url(:thumb) %></td>
                    <td class="image-description">
                    <%= image_tag app.image_url, :class => 'list-image' %>
                    </td>
                    <ul>App Name: <%= app.name%></ul>
                    <ul>Rating: <%= app.rating %></ul>
                    <ul><%= app.price %></ul>
                     <% if app.category %>
                     <p>
                    <ul><strong>Category:</strong><%= app.category.name %></ul>
                    </p>
                    </dl>         
                  </a>
                  </div>
                <% end %>
               <%end%>

                  </div>

                  </div>

                </div>
              </div>
              </div>
            </div>


            <div class="row">
        <div class="col-lg-4">  

        <h2><Strong>Sight Impairment</Strong></h2>


        <p><a href="apps#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
          
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="jumbotron">
                <div class="container">


                  <div class="row">

          <% @sightImpairment.limit(4).each do |app| %>
          <div class="col-xs-3" >        
          <a href="#" class="thumbnail" style="height:250px; width: 180px">         
        <dl>
          <td><%= image_tag app.image.url(:thumb) %></td>

          <td class="image-description">
          <%= image_tag app.image_url, :class => 'list-image' %>
        </td>
          <ul>App Name: <%= app.name%></ul>
          <ul>Rating: <%= app.rating %></ul>
          <ul><%= app.price %></ul>
          <% if app.category %>
        <p>
          <ul><strong>Category:</strong><%= app.category.name %></ul>
        </p>
          

        </dl>
                
          </a>
          </div>

        <% end %>
        <%end%>

                  </div>
                </div>
              
              </div>
              </div>
            </div>
          </div>

        
        <div class="row">
        <div class="col-lg-4">  

        <h2><Strong>learning Disabled</Strong></h2>


        <p><a href="apps#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
          
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="jumbotron">
                <div class="container">


                  <div class="row">
                  <div class="row">
          <% @learningDisabled.limit(4).each do |app| %>
          <div class="col-xs-3" >        
          <a href="#" class="thumbnail" style="height:250px; width: 180px">         
        <dl>
          <td><%= image_tag app.image.url(:thumb) %></td>

          <td class="image-description">
          <%= image_tag app.image_url, :class => 'list-image' %>
        </td>
          <ul>App Name: <%= app.name%></ul>
          <ul>Rating: <%= app.rating %></ul>
          <ul><%= app.price %></ul>
          <% if app.category %>
        <p>
          <ul><strong>Category:</strong><%= app.category.name %></ul>
        </p>
          

        </dl>
                
          </a>
          </div>

        <% end %>
        <%end%>

                  </div>
                </div>
              
              </div>
              </div>
            </div>
          </div>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2015 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/store/_product.html.erb
	<section class="product">
          <h2><%= link_to product.name, store_product_path(product) %></h2>
          <ul><%= product.rating %></ul>
          <ul><%= number_to_currency product.price %></ul>
          <td><%= image_tag product.image.url(:thumb) %></td>
        </dl>
        
        <td class="image-description">
          <%= image_tag product.image_url, :class => 'list-image' %>
        </td>

	</section>

app/views/store/index.html.erb
<h1>Store Listing</h1>

<% @products.each do |product| %>
		<section class="product">
          <h2><%= link_to product.name, store_product_path(product) %></h2>
          <ul><%= product.rating %></ul>
          <ul><%= number_to_currency product.price %></ul>
          <td><%= image_tag product.image.url(:thumb) %></td>
        </dl>
        
        <td class="image-description">
          <%= image_tag product.image_url, :class => 'list-image' %>
        </td>
        <% if product.category %>
        <p>
        	<strong>Category:</strong><%= product.category.name %>
        </p>
        <% end %>

	</section>
<%end%>

app/views/store/show.html.erb
	<section class="product">
          <h2><%= link_to @product.name, store_product_path(@product) %></h2>
          <ul><%= @product.rating %></ul>
          <ul><%= number_to_currency @product.price %></ul>
          <td><%= image_tag @product.image.url(:thumb) %></td>
        </dl>
        
        <td class="image-description">
          <%= image_tag @product.image_url, :class => 'list-image' %>
        </td>

        <% if @product.category %>
        <p>
        	<strong>Category:</strong><%= @product.category.name %>
        </p>
        <% end %>
	</section>

<p>
	<%= link_to "Home", root_path %>
</p>